"""empty message

Revision ID: e89740d35965
Revises: 
Create Date: 2026-09-02 18:16:37.854806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e89740d35965'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_content',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_context',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('workflow_state', sa.Enum('STARTED', 'CREATED', 'RUNNING', 'WAITING', 'COMPLETED', 'FAILED', name='workflow_state'), nullable=False),
    sa.Column('current_workflow_stage', sa.Enum('NONE', 'DISCOVER', 'FETCH', 'NORMALISE', 'DEDUPLICATE', 'ENTITY_RESOLUTION', 'ENRICH', 'PENDING_REVIEW', name='workflow_stage'), nullable=False),
    sa.Column('current_workflow_stage_state', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', 'NONE', name='workflow_stage_status'), nullable=True),
    sa.Column('context_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('errors', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_context_workflow_id'), 'workflow_context', ['workflow_id'], unique=False)
    op.create_table('article',
    sa.Column('article_state', sa.Enum('NEW', 'REVIEWING', 'SUMMARIZED', 'RETRIED', 'FAILED', name='article_state'), nullable=False),
    sa.Column('media_content_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_content_id'], ['media_content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_media_content_id'), 'article', ['media_content_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_media_content_id'), table_name='article')
    op.drop_table('article')
    op.drop_index(op.f('ix_workflow_context_workflow_id'), table_name='workflow_context')
    op.drop_table('workflow_context')
    op.drop_table('media_content')
    # ### end Alembic commands ###
